package xmlpulldemo;

public enum ParamValue {
			win_id,
			win_name,
			win_DataType,
			win_WinType,
			win_dwStyle,
			win_dwExStyle,
			
			lyr_type,
			lyr_status,
			lyr_intersts,
			lyr_clip_left,
			lyr_clip_right,
			lyr_clip_top,
			lyr_clip_boottom,
			lyr_zordeer,
			
			win_left,
			win_top,
			win_right,
			win_bottom,
			
			win_client_left,
			win_client_top,
			win_client_right,
			win_client_bottom,
			
			win_bkcolor,
			win_font,
			
			win_invalid_left,
			win_invalid_right,
			win_invalid_top,
			win_invalid_bottom,
			
			win_clip_left,
			win_clip_right,
			win_clip_top,
			win_clip_boottom,
			
			win_zordeer,
			
			win_callback,
			notify_proc,
			win_vscroll_minPos,
			win_vscroll_maxPos,
			win_vscroll_curPos,
			win_vscroll_pageStep,
			win_vscroll_barStart,
			win_vscroll_barLen,
			win_vscroll_status,
			
			win_hscroll_minPos,
			win_hscroll_maxPos,
			win_hscroll_curPos,
			win_hscroll_pageStep,
			win_hscroll_barStart,
			win_hscroll_barLen,
			win_hscroll_status,
			
			focus_bmp,
			unfocus_bmp,
			bmp_x,
			bmp_y,
			txt_x,
			txt_y,
			txt_align,
			text,
			focus_txt_color,
			unfocus_txt_color,
			font,
			charset,
			bkcolor,
			alpha,
			
			draw_sts,
			status,
			
			app_name,
			win_spCaption,
			win_spClassName,
			
			bmp_num,
			bmp_array,
			pos_num,
			pos_array,
			
			
			layer_work_mode_t,
			disp_ck_modet,
			pipe,
			alpha_en,
			alpha_val,
			scn_win_x,
			scn_win_y,
			scn_win_width,
			scn_win_height,
			src_win_x,
			src_win_y,
			src_win_width,
			src_win_heigth,
			
			channel,
			fb_size_width,
			fb_size_height,
			fb_add0,
			fb_add1,
			fb_add2,
			fb_type,
			
			lyrwin_sta,
			lyrwin_type,
			prio,
	;
}
